name: Run Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Give Cypress binary execute permission
      run: chmod +x node_modules/.bin/cypress

    - name: Install Cypress binary
      run: npx cypress install

    - name: Start static server
      run: |
        npx serve public -l 3000 &
        sleep 5

    - name: Run Cypress Tests
      run: npx cypress run
